/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfigLLM: typeof import('./src/components/llms/configLLM.vue')['default']
    CreateLLM: typeof import('./src/components/llms/createLLM.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FormItem: typeof import('./src/components/form/formItem.vue')['default']
    FormSelect: typeof import('./src/components/form/formSelect.vue')['default']
    FormSwitch: typeof import('./src/components/form/formSwitch.vue')['default']
    Info: typeof import('./src/components/icon/info.vue')['default']
    LForm: typeof import('./src/components/llms/lForm.vue')['default']
    LFormItem: typeof import('./src/components/llms/lFormItem.vue')['default']
    Log: typeof import('./src/components/conf/log.vue')['default']
    Logger: typeof import('./src/components/logger.vue')['default']
    SelectLLM: typeof import('./src/components/llms/selectLLM.vue')['default']
    Settings: typeof import('./src/components/icon/settings.vue')['default']
    Store: typeof import('./src/components/conf/store.vue')['default']
    User: typeof import('./src/components/conf/user.vue')['default']
  }
}
