/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/chat/chat.vue')['default']
    ConfigLLM: typeof import('./src/components/llms/configLLM.vue')['default']
    CreateLLM: typeof import('./src/components/llms/createLLM.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FormItem: typeof import('./src/components/form/formItem.vue')['default']
    FormSelect: typeof import('./src/components/form/formSelect.vue')['default']
    FormSwitch: typeof import('./src/components/form/formSwitch.vue')['default']
    Info: typeof import('./src/components/icon/info.vue')['default']
    JobCard: typeof import('./src/components/JobCard.vue')['default']
    LForm: typeof import('./src/components/llms/lForm.vue')['default']
    LFormItem: typeof import('./src/components/llms/lFormItem.vue')['default']
    Log: typeof import('./src/components/conf/log.vue')['default']
    SelectLLM: typeof import('./src/components/llms/selectLLM.vue')['default']
    Settings: typeof import('./src/components/icon/settings.vue')['default']
    Store: typeof import('./src/components/conf/store.vue')['default']
    User: typeof import('./src/components/conf/user.vue')['default']
  }
}
