// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const EffectScope: typeof import('vue')['EffectScope']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const JobList: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useJobList')['JobList']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const RequestError: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/request')['RequestError']
  const animate: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/index')['animate']
  const browser: typeof import('wxt/browser')['browser']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const customRef: typeof import('vue')['customRef']
  const deepmerge: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/deepmerge')['default']
  const defaultFormData: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useConfForm')['defaultFormData']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const delay: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/index')['delay']
  const effectScope: typeof import('vue')['effectScope']
  const elmGetter: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/elmGetter')['default']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const formDataKey: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useConfForm')['formDataKey']
  const formInfoData: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useConfForm')['formInfoData']
  const getCurDay: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/index')['getCurDay']
  const getCurTime: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/index')['getCurTime']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const getRootVue: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useVue')['getRootVue']
  const getStatistics: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useStatistics')['getStatistics']
  const h: typeof import('vue')['h']
  const inject: typeof import('vue')['inject']
  const injectScript: typeof import('wxt/client')['injectScript']
  const isPlainObject: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/deepmerge')['isPlainObject']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const jobList: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useJobList')['jobList']
  const jsonClone: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/deepmerge')['jsonClone']
  const loader: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/index')['loader']
  const logger: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/logger')['logger']
  const markRaw: typeof import('vue')['markRaw']
  const netConf: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/conf')['netConf']
  const nextTick: typeof import('vue')['nextTick']
  const notification: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/index')['notification']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const parseGptJson: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/parse')['parseGptJson']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const request: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/request')['request']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const setStatistics: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useStatistics')['setStatistics']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const statisticsKey: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useConfForm')['statisticsKey']
  const storage: typeof import('wxt/storage')['storage']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const todayKey: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useConfForm')['todayKey']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const updateStatistics: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useStatistics')['updateStatistics']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const useAttrs: typeof import('vue')['useAttrs']
  const useChat: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useChat')['useChat']
  const useCommon: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useCommon')['useCommon']
  const useConfFormData: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useConfForm')['useConfFormData']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useHookVueData: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useVue')['useHookVueData']
  const useHookVueFn: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useVue')['useHookVueFn']
  const useId: typeof import('vue')['useId']
  const useModel: typeof import('vue')['useModel']
  const useSlots: typeof import('vue')['useSlots']
  const useStatistics: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useStatistics')['useStatistics']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const useUserInfo: typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useStore')['useUserInfo']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ChatMessages, ChatMessage, ChatInput, ChatAvatar } from '/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useChat'
  import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useChat')
  // @ts-ignore
  export type { EncryptJobId, JobStatus, MyJobListData } from '/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useJobList'
  import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useJobList')
  // @ts-ignore
  export type { NetConf, NotificationAlert, NotificationMessage, NotificationNotification } from '/home/q/dev/personal/monkey-extension/boos-helper/src/utils/conf'
  import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/conf')
  // @ts-ignore
  export type { DeepmergeOptions } from '/home/q/dev/personal/monkey-extension/boos-helper/src/utils/deepmerge'
  import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/deepmerge')
  // @ts-ignore
  export type { ResponseType, OnStream, RequestArgs } from '/home/q/dev/personal/monkey-extension/boos-helper/src/utils/request'
  import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/request')
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly ContentScriptContext: UnwrapRef<typeof import('wxt/client')['ContentScriptContext']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly InvalidMatchPattern: UnwrapRef<typeof import('wxt/sandbox')['InvalidMatchPattern']>
    readonly JobList: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useJobList')['JobList']>
    readonly MatchPattern: UnwrapRef<typeof import('wxt/sandbox')['MatchPattern']>
    readonly MigrationError: UnwrapRef<typeof import('wxt/storage')['MigrationError']>
    readonly RequestError: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/request')['RequestError']>
    readonly animate: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/index')['animate']>
    readonly browser: UnwrapRef<typeof import('wxt/browser')['browser']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createIframeUi: UnwrapRef<typeof import('wxt/client')['createIframeUi']>
    readonly createIntegratedUi: UnwrapRef<typeof import('wxt/client')['createIntegratedUi']>
    readonly createShadowRootUi: UnwrapRef<typeof import('wxt/client')['createShadowRootUi']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly deepmerge: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/deepmerge')['default']>
    readonly defaultFormData: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useConfForm')['defaultFormData']>
    readonly defineAppConfig: UnwrapRef<typeof import('wxt/sandbox')['defineAppConfig']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineBackground: UnwrapRef<typeof import('wxt/sandbox')['defineBackground']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineConfig: UnwrapRef<typeof import('wxt')['defineConfig']>
    readonly defineContentScript: UnwrapRef<typeof import('wxt/sandbox')['defineContentScript']>
    readonly defineUnlistedScript: UnwrapRef<typeof import('wxt/sandbox')['defineUnlistedScript']>
    readonly defineWxtPlugin: UnwrapRef<typeof import('wxt/sandbox')['defineWxtPlugin']>
    readonly delay: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/index')['delay']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly elmGetter: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/elmGetter')['default']>
    readonly fakeBrowser: UnwrapRef<typeof import('wxt/testing')['fakeBrowser']>
    readonly formDataKey: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useConfForm')['formDataKey']>
    readonly formInfoData: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useConfForm')['formInfoData']>
    readonly getCurDay: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/index')['getCurDay']>
    readonly getCurTime: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/index')['getCurTime']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getRootVue: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useVue')['getRootVue']>
    readonly getStatistics: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useStatistics')['getStatistics']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly injectScript: UnwrapRef<typeof import('wxt/client')['injectScript']>
    readonly isPlainObject: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/deepmerge')['isPlainObject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly jobList: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useJobList')['jobList']>
    readonly jsonClone: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/deepmerge')['jsonClone']>
    readonly loader: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/index')['loader']>
    readonly logger: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/logger')['logger']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly netConf: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/conf')['netConf']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly notification: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/index')['notification']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly parseGptJson: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/parse')['parseGptJson']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly request: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/utils/request')['request']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setStatistics: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useStatistics')['setStatistics']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly statisticsKey: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useConfForm')['statisticsKey']>
    readonly storage: UnwrapRef<typeof import('wxt/storage')['storage']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly todayKey: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useConfForm')['todayKey']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly updateStatistics: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useStatistics')['updateStatistics']>
    readonly useAppConfig: UnwrapRef<typeof import('wxt/client')['useAppConfig']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useChat: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useChat')['useChat']>
    readonly useCommon: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useCommon')['useCommon']>
    readonly useConfFormData: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useConfForm')['useConfFormData']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useHookVueData: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useVue')['useHookVueData']>
    readonly useHookVueFn: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useVue')['useHookVueFn']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useStatistics: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useStatistics')['useStatistics']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useUserInfo: UnwrapRef<typeof import('/home/q/dev/personal/monkey-extension/boos-helper/src/hooks/useStore')['useUserInfo']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}
